### PR TITLE
Fix broken MySQL and SQLite tests

### PR DESCRIPTION
**Pull request by jamis**
Rather than trying to preserve backwards compatibility for jRuby < 9k, this branch proposes that we simply move into the future with `Module#prepend` and ask that jRuby users remain on the earlier Spectacles releases.

This lets us use a clean solution to the problem of dependency loading (use of the `inherited` hook to autoload Spectacles means that methods we try to override on the base class will be defined BEFORE the corresponding methods of the base class). 

* Retrain #tables method on SQLite and MySQL adapters to return only tables
* use Module#prepend to load #tables overrides properly
* remove sqlite adapter as it is no longer supported in ActiveRecord

### CODE REVIEW

**Comment by jamis** [comment]
@liveh2o thoughts on this? I'd really like to move forward with this approach, as using `Module#prepend` makes for a very, very clean solution here (compared to the hackish solution proposed by pull request #13).

**Comment by liveh2o** [comment]
:shipit:

**Comment by jamis** [comment]
Just to confirm, @liveh2o, when you said "bump major version", you meant going all the way to 1.0 now, right? If you're good with that, I'll make that change, merge this to master, and push a new release.

**Comment by liveh2o** [comment]
Yes indeed.

tumblr_mcm8s9mpru1qdpq8c

**Pull request merged**
