### PR TITLE
only get views that we own

### LINKED ISSUE #22: Only dump definitions for views we own
In production we have a postgres extension loaded which provides a view called `pg_stat_statements`, but that view is not queryable by the database user we are authenticating with.

We could use this SQL to only find views which where created by our database user (ie the ones we have created and managed via rails).

```sql
SELECT  n.nspname AS table_schema
,        pg_catalog.pg_get_userbyid(c.relowner) AS table_owner
,        c.relname AS table_name
FROM pg_catalog.pg_class c
LEFT JOIN pg_catalog.pg_namespace n ON (n.oid = c.relnamespace)
WHERE c.relkind  = 'v' AND n.nspname ='public' and  pg_catalog.pg_get_userbyid(c.relowner)='DATABASE_USER_NAME';
```

I'm not sure yet how to get the `DATABASE_USER_NAME` from activerecord, but I would think it would be available as part of the connection.

### PR DESCRIPTION
**Pull request by mmmries**
When querying for a list of views to dump into the schema.rb file, add a join and condition that the current database user must be the owner of a view before we decide to dump it into the schema
Fixes #22 

The use case here is that in production we have the `pg_stat_statements` extension turned on which adds a `pg_stat_statements` view, but it is not readable by our rails database user. This was throwing a postgres permission error when we tried to get the definition of the view and add it to the schema.rb.

This change to the query makes sure the "default" credentials being used by ActiveRecord to access the database is the user that created a given view before it tries to get its definition.

I've tested this locally with an app at work, but I don't know enough about postgres and ActiveRecord internals to confidently say that this will work everywhere.

/cc @abrandoned @liveh2o @brianstien @jamis

### CODE REVIEW

**Comment by liveh2o** [comment]
The only issues that I can think of would be a specific version of Postgres not having support for the `pg_class` table and `pg_catalog` function, or the user not having permission to view those things. I think the latter is much more likely than the former. If we've tried it under a few versions or permissions setups, then let's roll with this.

**Comment by mmmries** [comment]
So far I've run it locally against my postgres `9.4.4` database. I'll try it against a few other version of postgres that I can find at hand and report back my findings.

**Comment by mmmries** [comment]
I haven't found any postgres versions earlier than `9.4.2` to test on, but it looks like the `information_schema.tables` view is actually defined by accessing the `pg_class` table.

```sql
 SELECT current_database()::information_schema.sql_identifier AS table_catalog,
    nc.nspname::information_schema.sql_identifier AS table_schema,
    c.relname::information_schema.sql_identifier AS table_name,
        CASE
            WHEN nc.oid = pg_my_temp_schema() THEN 'LOCAL TEMPORARY'::text
            WHEN c.relkind = 'r'::"char" THEN 'BASE TABLE'::text
            WHEN c.relkind = 'v'::"char" THEN 'VIEW'::text
            WHEN c.relkind = 'f'::"char" THEN 'FOREIGN TABLE'::text
            ELSE NULL::text
        END::information_schema.character_data AS table_type,
    NULL::character varying::information_schema.sql_identifier AS self_referencing_column_name,
    NULL::character varying::information_schema.character_data AS reference_generation,
        CASE
            WHEN t.typname IS NOT NULL THEN current_database()
            ELSE NULL::name
        END::information_schema.sql_identifier AS user_defined_type_catalog,
    nt.nspname::information_schema.sql_identifier AS user_defined_type_schema,
    t.typname::information_schema.sql_identifier AS user_defined_type_name,
        CASE
            WHEN c.relkind = 'r'::"char" OR (c.relkind = ANY (ARRAY['v'::"char", 'f'::"char"])) AND (pg_relation_is_updatable(c.oid::regclass, false) & 8) = 8 THEN 'YES'::text
            ELSE 'NO'::text
        END::information_schema.yes_or_no AS is_insertable_into,
        CASE
            WHEN t.typname IS NOT NULL THEN 'YES'::text
            ELSE 'NO'::text
        END::information_schema.yes_or_no AS is_typed,
    NULL::character varying::information_schema.character_data AS commit_action
   FROM pg_namespace nc
     JOIN pg_class c ON nc.oid = c.relnamespace
     LEFT JOIN (pg_type t
     JOIN pg_namespace nt ON t.typnamespace = nt.oid) ON c.reloftype = t.oid
  WHERE (c.relkind = ANY (ARRAY['r'::"char", 'v'::"char", 'f'::"char"])) AND NOT pg_is_other_temp_schema(nc.oid) AND (pg_has_role(c.relowner, 'USAGE'::text) OR has_table_privilege(c.oid, 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER'::text) OR has_any_column_privilege(c.oid, 'SELECT, INSERT, UPDATE, REFERENCES'::text));
```

This makes me think it is very unlikely that we will run into a permissions issue with joining to `pg_class`. I've also found `pg_getuserbyid` documented back to [at least postgres 8.4](http://www.postgresql.org/docs/8.4/static/functions-info.html). This makes me feel pretty confident that permissions or function availability shouldn't be an issue for us.

**Comment by jamis** [comment]
:+1: I've seen `pg_class` used (and used it myself) in many places. I think it's pretty safe to rely on for this.

**Comment by liveh2o** [comment]
Sweet

tumblr_mcm8s9mpru1qdpq8c

**Pull request merged**
